#Zad 1
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
c = (a**2 + b**2)
print("Pole to:", c, " cm^2")
print("")
#Zad 2
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
c = ((a+b)**2)
print("Kwadrat sumy dwóch liczb wynosi:", c)
print("")
#Zad 3
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
c = ((a-b)**3)
print("Sześcian różnicy dwóch liczb wynosi:", c)
print("")
#Zad 4
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
c = int(input("Wprowadź liczbę 3: ", ))
d = (a*b*c)
print("Iloczyn trzech liczb wynosi:", d)
print("")
#Zad 5
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
print((2*(a+b))/5)
print((a+b)*0.4)
print("")
#Zad 6
brutto = float(input("Wprowadź liczbę kwotę brutto: ", ))
VAT = (brutto*1.23)
print("Kwota z watem: ", round(VAT,2))
print("")
#Zad 7
a = int(input("Wprowadź liczbę 1: ", ))
b = int(input("Wprowadź liczbę 2: ", ))
c = (a%b)
print(c)
